name: Publish-Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., v1.0.0 or latest)'
        required: false
        default: 'latest'

permissions:
  contents: read
  packages: write
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # Lint the code with gofmt
      - name: Lint with gofmt
        run: test -z "$(gofmt -l .)"

      # Build the Go application
      - name: Build the application
        run: go build -o tigerbeetle_api .

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # GitHub automatically provides a GITHUB_TOKEN secret to authenticate
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          # Set to true to push the image to the registry
          push: true
          # Define the tags for the image
          tags: |
            ghcr.io/${{ github.repository_owner }}/tigerbeetle_api:latest
            ghcr.io/${{ github.repository_owner }}/tigerbeetle_api:${{ github.sha }}

      # (Optional) Display Docker image details
      - name: Show Docker images
        run: docker images
